### PR TITLE
add direct link to ux simulation

### PR DESCRIPTION
**Pull request by codenoid**

### CODE REVIEW

**Comment by muizidn** [comment]
Very productive. Thanks. Could you please improve its description? You can add Try UX simulation instead

**Comment by codenoid** [comment]
btw direct link to rails seems broken

**Comment by muizidn** [comment]
Oh yes. We’ve updated the implementation to use flask instead.

**Comment by codenoid** [comment]
moved to #7 , bcoz this was PR was using direct-edit (non-fork)

**Pull request closed without merging**
